version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python django/manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
